### ISSUE TITLE
Issues getting the Web UI to start/play music

### ISSUE THREAD

**Issue by GoldenChaos** [drensin/Remixatron#10]
Attempted to run the web UI, but got the following error even though I have the requests module installed.

```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    import requests
ImportError: No module named requests
```

This is the command I'm running to start it up:

`python3 -m pip install --upgrade youtube-dl; python main.py`

**Comment by drensin** [comment]
Is this running in a virtual environment?  If so, you need to re-install
all the dependencies for each environment.  Just do a pip install -r
requirements.txt to grab everything.

-dave

**Comment by GoldenChaos** [comment]
It's not running in a virtual environment that I'm aware of. Running pip install -r requirements.txt just tells me that all the requirements are satisfied:

```
Jason@Lancer Web UI % python3 -m pip install -r requirements.txt                 
Requirement already satisfied: audioread==2.1.8 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 1)) (2.1.8)
Requirement already satisfied: certifi==2019.6.16 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2019.6.16)
Requirement already satisfied: cffi==1.12.3 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 3)) (1.12.3)
Requirement already satisfied: chardet==3.0.4 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: Click==7.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (7.0)
Requirement already satisfied: decorator==4.4.0 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 6)) (4.4.0)
Requirement already satisfied: dnspython==1.16.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: eventlet==0.25.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (0.25.0)
Requirement already satisfied: Flask==1.1.1 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (1.1.1)
Requirement already satisfied: Flask-Compress==1.4.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.4.0)
Requirement already satisfied: Flask-SocketIO==4.2.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (4.2.0)
Requirement already satisfied: greenlet==0.4.15 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (0.4.15)
Requirement already satisfied: idna==2.8 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (2.8)
Requirement already satisfied: itsdangerous==1.1.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (1.1.0)
Requirement already satisfied: Jinja2==2.10.1 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (2.10.1)
Requirement already satisfied: joblib==0.13.2 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 16)) (0.13.2)
Requirement already satisfied: librosa==0.7.0 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 17)) (0.7.0)
Requirement already satisfied: llvmlite==0.29.0 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 18)) (0.29.0)
Requirement already satisfied: MarkupSafe==1.1.1 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (1.1.1)
Requirement already satisfied: monotonic==1.5 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 20)) (1.5)
Requirement already satisfied: numba==0.45.1 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 21)) (0.45.1)
Requirement already satisfied: numpy==1.17.0 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 22)) (1.17.0)
Requirement already satisfied: pycparser==2.19 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 23)) (2.19)
Requirement already satisfied: python-engineio==3.9.2 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 24)) (3.9.2)
Requirement already satisfied: python-socketio==4.3.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 25)) (4.3.0)
Requirement already satisfied: requests==2.22.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 26)) (2.22.0)
Requirement already satisfied: resampy==0.2.1 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 27)) (0.2.1)
Requirement already satisfied: scikit-learn==0.21.3 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 28)) (0.21.3)
Requirement already satisfied: scipy==1.3.0 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 29)) (1.3.0)
Requirement already satisfied: six==1.12.0 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 30)) (1.12.0)
Requirement already satisfied: SoundFile==0.10.2 in /Users/Jason/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 31)) (0.10.2)
Requirement already satisfied: urllib3==1.25.3 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 32)) (1.25.3)
Requirement already satisfied: Werkzeug==0.15.5 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 33)) (0.15.5)
Requirement already satisfied: youtube-dl==2019.8.2 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 34)) (2019.8.2)
```

**Comment by GoldenChaos** [comment]
Oh my god I'm stupid, there are two python commands in there and the second command was not referencing python3.

**Comment by drensin** [comment]
ok.. let's try this:

cd "Remixatron/Web UI"
python3.7 -m venv remixatron.env      # creates a virtual environment for
this project
source remixatron.env/bin/activate     # activates it
python --version                                  #  should say Paython
3.7.x
pip install -r requirements.txt               # installs all the
requirements to that env
python main.py                                    # run the app

-dave

**Comment by drensin** [comment]
:-)

**Comment by GoldenChaos** [comment]
Now I have a real error for you!

```
/usr/local/opt/python/bin/python3.7: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py')
```

**Comment by drensin** [comment]
did you cd into "Remixatron/Web UI" ?

-dave

**Comment by GoldenChaos** [comment]
Yup, here's what I ran and where:

```
Jason@Lancer Web UI % python3 -m pip install --upgrade youtube-dl; python3 -m main.py
```

**Comment by GoldenChaos** [comment]
Aha! I had to remove the `-m` attribute from the second command. It's running now :D

**Comment by GoldenChaos** [comment]
Reopening because of an issue with uploading music:

```
t_kvMPlJn-t5rWWsUHUpdQ uploaded: test.mp3
objc[62787]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[62787]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

Python then crashes.

EDIT: The same issue occurs when using a YouTube URL.

**Comment by GoldenChaos** [comment]
Progress: apparently you must run `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`. I'm not really sure what Fork is or if this is a safe thing to do, but I got a new error that feels closer to things working:

```
t_kvMPlJn-t5rWWsUHUpdQ uploaded: test.mp3
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 370, in process_audio
    fn = fetch_from_local(url, userid)
  File "main.py", line 219, in fetch_from_local
    stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'
```

EDIT: Seems like the solution is to install ffmpeg with Homebrew; doing that now.

**Comment by GoldenChaos** [comment]
Things seem to work now, but the whole thing still dies before it gets to playing a song. Audio will appear to upload and get processed according to the command line, but nothing happens in the browser, and music never starts playing:

![Screen Shot 2019-08-04 at 6 50 54 PM](https://user-images.githubusercontent.com/1396727/62430307-f58f7c00-b6e8-11e9-8dd6-268ea07a3440.png)

EDIT: The same thing occurs when using a YouTube URL; the audio will successfully download, but after that the same thing happens.

**Comment by GoldenChaos** [comment]
Pulling up the inspector, it seems to be a CORS issue?

![Screen Shot 2019-08-04 at 7 01 39 PM](https://user-images.githubusercontent.com/1396727/62430390-57041a80-b6ea-11e9-831b-4e852f5bc121.png)

That's as deep as I can go for now, I think...

**Comment by drensin** [comment]
hmm...  This is.. unexpected...  Try this:  rename the cors.cfg file to cors.cfg.old and retry...  I'm curious if that fixes it.  Also, if you happen to have Chrome installed, can you try that, too?  (I'm curious if this is a Safari thing.)

**Comment by GoldenChaos** [comment]
Yup, it's a safari issue (and changing cors.cfg to cors.cfg.old didn't fix it). I've got audio playing now in chrome, but it sounds choppy - it skips slightly with each beat. Is there a reason this would be happening?

EDIT: It only happens with uploaded files. YouTube audio is seamless.

**Comment by drensin** [comment]
well that's no good... The audio timing routing in the client javascript
might not be quite right (although it sound fine on all of my machines and
phones).   Do you happen to have any way to record what you are hearing?

**Comment by GoldenChaos** [comment]
https://vocaroo.com/i/s0CZXKZA5KtX

The recording sounds like crap since I literally used voice memos but you get the idea, haha.

**Comment by drensin** [comment]
Do you mind sending me the original file?

**Comment by GoldenChaos** [comment]
https://vocaroo.com/media_command.php?media=s0uuvPiRKG7H&command=download_mp3

**Comment by drensin** [comment]
ok.. I can reproduce it (but am not entirely sure what's going on).  By any
chance, do you have a piece of music that's at a slower (preferably a much
slower) BPM that you can try?  I have a theory about this, but I'm curious
to see.

**Comment by GoldenChaos** [comment]
Can confirm that the lower BPM song did not have the intense skipping issues. It did skip _very_ subtly every few beats, though.

MP3: https://vocaroo.com/media_command.php?media=s1VW6ccMIDIB&command=download_mp3

**Comment by wantsomechocolate** [comment]
Running Remixatron Web UI with Windows Subsystem for Linux:
I got stuck after the loading screen got to 100% as well. Sometimes I would get no error, and sometimes I would get an error in the terminal like `send_file() got an unexpected keyword argument 'cache_timeout'` or an error in the javascript console like `GET http://localhost:8000/getaudio?0.randomsequenceofnumbers 404 (NOT FOUND)`

![terminal](https://user-images.githubusercontent.com/2631892/187554633-d9de66e9-1dd7-4721-aad0-c647c6119f31.jpg)

 I suspected the problem was because I was using wsl to create the virtual env and run the script. These are the things I had to do to get it working:

1. Update cors.cfg to something like:
`{"ORIGINS":["http://localhost:8000", "http://my.ip.address:8000"]}`
2. Add flask_cors:
`pip install flask_cors` (after you activate your virtual env, of course)
Then directly below `app = Flask(__name__)` in main.py, add this line:
`CORS(app)`
3. Fix path issues:
I noticed that main.py is using `Path.home()` and `tempfile.gettempdir()`, both of which were returning paths on the linux subsystem and not the windows system. 

     - I updated remixatron_dir to be a windows path by replacing
`remixatron_dir = (Path.home() / '.remixatron')`
with
`path_home = '/mnt/c/path/to/somewhere/on/windows'`
`remixatron_dir = Path(os.path.join(path_home, '.remixatron'))`

     - Then I created my own tmp_dir like below and replaced all instances of `tempfile.gettempdir()` with `tmp_dir`
```
tmp_dir = os.path.join(remixatron_dir,'tmp')
if Path(tmp_dir).exists() == False:
    os.mkdir(tmp_dir)
``` 
4. Address the send_file() error from above
Inside the `get_audio` function I changed
`return send_from_directory(tmp_dir + '/', get_userid() + '.mp3', cache_timeout=0)`
to
`return send_from_directory(tmp_dir + '/', get_userid() + '.mp3') #, cache_timeout=0)`
I'm probably breaking something by doing this, but I haven't noticed anything, yet. 
5. Some notes on the install process
To get everything installed in the first place I had to do some sudo apt installs and also had to change from using dbus-python to dbus-next, which is apparently it's successor.
`sudo apt install libdbus-1-3 libdbus-1-dev libcairo2-dev pkg-config python3-dev` (I think that's everyone)
`pip install dbus-next` (different package, but I didn't have to make any code changes). 

I'm not 100% sure I needed to do all of these things necessarily, but I tried removing all the "fixes" and add them back in one by one and eventually had to add them all back in, still doesn't mean I need them all because I didn't test every combination, but at least it's working for me now. 

Thanks.
