### ISSUE TITLE
Error for operands which could not be broadcast together with shapes

### ISSUE THREAD

**Issue by DyeffersonAz** [drensin/Remixatron#12]
Here is the log from my Linux terminal:
``` [#####     ] Testing a cluster value of 48...Traceback (most recent call last):
                                                                                 File "infinite_jukebox.py", line 263, in <module>
                                                      progress_callback=MyCallback, do_async=False, use_v1=args.use_v1)
                                         File "/home/dyefferson/Downloads/Remixatron-master/Remixatron.py", line 164, in __init__
                                                     self.__process_audio()
                                                                             File "/home/dyefferson/Downloads/Remixatron-master/Remixatron.py", line 299, in __process_audio
                self.clusters, seg_ids = self.__compute_best_cluster_with_sil(evecs, Cnorm)
             File "/home/dyefferson/Downloads/Remixatron-master/Remixatron.py", line 706, in __compute_best_cluster_with_sil
                                                X = evecs[:, :n_clusters] / Cnorm[:, n_clusters-1:n_clusters]
                             ValueError: operands could not be broadcast together with shapes (18,18) (18,0) 
```
If this is a problem coming from the mp3 I'm taking, could this be fixed in anyway?

**Comment by drensin** [comment]
Thanks for the bug report!  Some questions:

1) Have you tried the Web UI version of the app (located in the Web UI
subdir).  I'm curious if it gets the same error..
2) Do any MP3s work or are they all broken?
3) If it's just this particular MP3, could you share it with me?  That will
really help me debug...

**Comment by DyeffersonAz** [comment]
1) The Web UI version gives me the same error via terminal
2) I've tried other mp3s and they work, but not as the "Eternal Jukebox" or "Infinite Jukebox", sometimes the song is interrupted to be started again, it is not perfect.
3) It is: https://freesound.org/people/mansardian/sounds/61322/

**Comment by cfreemoser** [comment]
@drensin @DyeffersonAz could you folks ever found a solution? Hit the same error today :/ 

```
47.0%: Testing a cluster value of 48...
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 449, in process_audio
    start_beat=0, do_async=False)
  File "/app/Remixatron.py", line 169, in __init__
    self.__process_audio_madmom()
  File "/app/Remixatron.py", line 664, in __process_audio_madmom
    self.clusters, seg_ids = self.__compute_best_cluster_with_sil(evecs, Cnorm)
  File "/app/Remixatron.py", line 935, in __compute_best_cluster_with_sil
    X = evecs[:, :n_clusters] / Cnorm[:, n_clusters-1:n_clusters]
ValueError: operands could not be broadcast together with shapes (10,10) (10,0)
```

**Comment by DyeffersonAz** [comment]
@cfreemoser There's a long time since I've seen this. I have never found a solution for it, though.
