### ISSUE TITLE
Problem with installing dependencies

### ISSUE THREAD

**Issue by WerySkok** [drensin/Remixatron#17]
I use Windows 10 x64 with Python 3.9 and I get this message when I try to install dependencies:
```
Using cached pygame-1.9.6.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\werys\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\werys\\AppData\\Local\\Temp\\pip-install-2jnvf5w6\\pygame_e700e0e5a81f423a88656774081013ca\\setup.py'"'"'; __file__='"'"'C:\\Users\\werys\\AppData\\Local\\Temp\\pip-install-2jnvf5w6\\pygame_e700e0e5a81f423a88656774081013ca\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\werys\AppData\Local\Temp\pip-pip-egg-info-fqmgny97'
         cwd: C:\Users\werys\AppData\Local\Temp\pip-install-2jnvf5w6\pygame_e700e0e5a81f423a88656774081013ca\
    Complete output (17 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...


    Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\werys\AppData\Local\Temp\pip-install-2jnvf5w6\pygame_e700e0e5a81f423a88656774081013ca\setup.py", line 194, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\werys\AppData\Local\Temp\pip-install-2jnvf5w6\pygame_e700e0e5a81f423a88656774081013ca\buildconfig\config.py", line 210, in main
        deps = CFG.main(**kwds)
      File "C:\Users\werys\AppData\Local\Temp\pip-install-2jnvf5w6\pygame_e700e0e5a81f423a88656774081013ca\buildconfig\config_win.py", line 576, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\werys\AppData\Local\Temp\pip-install-2jnvf5w6\pygame_e700e0e5a81f423a88656774081013ca\buildconfig\download_win_prebuilt.py", line 302, in ask
        reply = raw_input(
    EOFError: EOF when reading a line
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz#sha256=301c6428c0880ecd4a9e3951b80e539c33863b6ff356a443db1758de4f297957 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pygame==1.9.6
ERROR: No matching distribution found for pygame==1.9.6
```

**Comment by drensin** [comment]
ah yes.. Building/running the command line interface on Windows isn't
likely to work anytime soon.  Too many missing dependencies. :-)

Have you tried the Web UI?  That runs well on Windows.

-dave
