### ISSUE TITLE
Uploading files results in errors

### ISSUE THREAD

**Issue by RyanTheAvian** [drensin/Remixatron#18]
So I have installed everything for Remixatron, but I am not sure if I should install either the Python version of FFMPEG, or the Windows version. So I installed the Python version, and that didn't fix a error I got before. The error I am getting is from uploading a mp3 to the website.

[2021-03-20 10:48:54,364] ERROR in app: Exception on /upload_audio [POST]
Traceback (most recent call last):
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\CFS\Desktop\Remixatron-master\Web_UI\main.py", line 656, in upload_audio
    file.save(of)
  File "C:\Users\CFS\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\datastructures.py", line 3066, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ZPVkl1wYmZGzv6MAY-pPQQ.tmp'

**Comment by LunaUrsa** [comment]
This issue is because the program doesn't know the right directory to save/load stuff from.

For example I changed:
`of = '/tmp/' +deviceid + '.tmp'`

to

`of = os.path.dirname(os.path.abspath(__file__)) + '/tmp/' +deviceid + '.tmp'`

I did this for most mentions of /tmp/ so that it knows to use the current directory and it got past that error, but now it just hangs on "Starting playback". 

I'll give it another look when I'm not at work, figured I'd document what I've done so far in case I forget to come back and someone else can take it from here. 

I'm on Windows 10, Python 3.9, ffmpeg installed sometime ago, pretty sure it's not the most recent version.

**Comment by drensin** [comment]
good catch on this.  It definitely will break on Windows.  Rather than the
approach you are taking, have you looked at this
<https://docs.python.org/3/library/tempfile.html> ?

-dave

**Comment by LunaUrsa** [comment]
I gave it a shot over the weekend but I'm honestly not the best coder, I'm stuck on converting the request.file mp3 upload into a "tempfile" object. 

Also, each tempfile has a mostly-random name which will make caching complicated too. I'm not giving up, but if someone else wants to take a shot I wont be offended.

**Comment by taxminion** [comment]
Windows 10 and I have basically no experience with Python or things of this nature. Getting main.py to work at all was quite the journey.

I kept getting errors like
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
trying to run it from the command window (`py main.py`) but when I run main.py directly it actually works and I can access the Web UI through localhost. However, any attempt to load music gives the same tmp errors as those above.

Is Remixatron just not usable on Windows?
