### ISSUE TITLE
Need help with installing

### ISSUE THREAD

**Issue by ghost** [drensin/Remixatron#21]
Heya! I'm kinda new to python, Cold you maybe give me instructions on how to install it?

**Comment by drensin** [comment]
what platform are you using?  Windows, Mac, or Linux?

**Comment by ghost** [comment]
Windows

**Comment by drensin** [comment]
don't use the command line in Windows.  It will break badly.  Instead, use
the GUI version: https://github.com/drensin/Remixatron/tree/master/Web%20UI

**Comment by ghost** [comment]
And how do I install that?

**Comment by drensin** [comment]
the installation instructions are on the page.  Just scroll down.  (also in
the readme.md)

**Comment by ghost** [comment]
How do I install using pip install --upgrade pip in the first place? I don't really know these kind of things.

**Comment by drensin** [comment]
ok.. sounds like you need to find a quickstart "how do I install Python and
PIP on Windows".
https://www.google.com/search?q=how+do+I+install+python+on+windows&oq=how+do+I+install+python+on+windows&aqs=chrome..69i57j0i512l6j0i22i30l3.8984j0j7&sourceid=chrome&ie=UTF-8

**Comment by ghost** [comment]
Every time I do step 4 It brings me to the microsoft store.

**Comment by drensin** [comment]
honestly, I don't use Windows so I really don't know :-(

**Comment by ghost** [comment]
What does this mean then?: On Windows make sure you add the following directories to your Path

**Comment by ghost** [comment]
And how do I start up the server?

**Comment by ghost** [comment]
Ok. So I got it to work, but when I try with a song I get this error: FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by drensin** [comment]
are you feeding it your own file or are you pasting a link from youtube?

**Comment by ghost** [comment]
I tried both.

**Comment by drensin** [comment]
can you cut/paste the complete error output from your command window?

**Comment by ghost** [comment]
Yoz3zYsQtkWMR8f61lilcA has connected
Yoz3zYsQtkWMR8f61lilcA uploaded: 01 Get Dirty.m4a
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nieks\Web UI\main.py", line 384, in process_audio
    fn = fetch_from_local(url, userid)
  File "C:\Users\nieks\Web UI\main.py", line 227, in fetch_from_local
    result = subprocess.run(['ffmpeg', '-y', '-i', fn, '-af', filter, of],
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by drensin** [comment]
you need to install a program called ffmpeg.  There are installers for
windows.

**Comment by ghost** [comment]
I have the program.

**Comment by ghost** [comment]
Do I have to do something to install it?

**Comment by drensin** [comment]
it needs to be in a place where Remixatron can find it.  If it's just one
executable (ffmpeg.exe) you could put it in the same directory as the Web
GUI code.  That would solve it.

-daev

**Comment by ghost** [comment]
Where is that code?

**Comment by drensin** [comment]
let's backup... Did you do this bit from the install?

On Windows make sure you add the following directories to your Path:

# The directory where you installed ffmpeg.exe, eg:
C:\ffmpeg\bin
# The python subdirectory where youtube-dl.exe was installed, eg:
C:\Users\Name\AppData\Roaming\Python\Python36\Scripts

<https://github.com/drensin/Remixatron/tree/master/Web%20UI#running>

**Comment by ghost** [comment]
Yoz3zYsQtkWMR8f61lilcA has connected
Yoz3zYsQtkWMR8f61lilcA asked for: https://www.youtube.com/watch?v=0CGVgAYJyjk with 0 clusters and useCache of True
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nieks\Web UI\main.py", line 382, in process_audio
    fn = fetch_from_youtube(url,userid)
  File "C:\Users\nieks\Web UI\main.py", line 184, in fetch_from_youtube
    result = [line.decode(encoding="utf-8") for line in subprocess.check_output(cmd).splitlines()]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified


And this is with the url.

**Comment by drensin** [comment]
right. it can't find youtube-dl.  Have you downloaded/installed that
program?  https://ytdl-org.github.io/youtube-dl/download.html

**Comment by ghost** [comment]
pip install --upgrade youtube-dl; python main.py
Requirement already satisfied: youtube-dl in c:\users\nieks\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (2021.6.6)
ERROR: Could not find a version that satisfies the requirement python (from versions: none)
ERROR: No matching distribution found for python

**Comment by ghost** [comment]
That's what I got.

**Comment by drensin** [comment]
Type youtube-dl at a command prompt and tell me what you see.
