### ISSUE TITLE
error during "computing final beat array..." on WebUI

### ISSUE THREAD

**Issue by yasminpierazo** [drensin/Remixatron#22]
I'm using Windows 10 and its crashing during "computing final beat array...", here's the log:

```
80.0%: computing final beat array...
Process Process-5:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Yasmin\Desktop\Web UI\main.py", line 407, in process_audio
    jukebox = InfiniteJukebox(fn, clusters=clusters,
  File "C:\Users\Yasmin\Desktop\Web UI\Remixatron.py", line 164, in __init__
    self.__process_audio()
  File "C:\Users\Yasmin\Desktop\Web UI\Remixatron.py", line 456, in __process_audio
    beats[last_chance]['next'] = min(beats[last_chance]['jump_candidates'])
ValueError: min() arg is an empty sequence

```
That's the error, but it doesn't crash on every song.  Can someone help me pls?

**Comment by FlashlightET** [comment]
same!
