### ISSUE TITLE
Error when calculating the final array of bits in the console / WEB UI

### ISSUE THREAD

**Issue by Idol11112222** [drensin/Remixatron#23]
I'm running a test file in .mp3 format:

C:\Users\MyUser\Remixatron>python infinite_jukebox.py Test.mp3 -save TestRemix -duration 360

Gives me the following:
```
pygame 2.1.2 (SDL 2.0.18, Python 3.10.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'Test.mp3': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyUser\Remixatron\infinite_jukebox.py", line 262, in <module>
    jukebox = InfiniteJukebox(filename=args.filename, start_beat=args.start, clusters=args.clusters,
  File "C:\Users\MyUser\Remixatron\Remixatron.py", line 164, in __init__
    self.__process_audio()
  File "C:\Users\MyUser\Remixatron\Remixatron.py", line 187, in __process_audio
    y, sr = librosa.core.load(self.__filename, mono=False, sr=None)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Test.mp3'

C:\Users\MyUser\Remixatron>python infinite_jukebox.py Test.mp3 -save TestRemix -duration 360
pygame 2.1.2 (SDL 2.0.18, Python 3.10.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
C:\Users\MyUser\Remixatron\Remixatron.py:190: FutureWarning: Pass y=[[-0.02310181 0.0262146 0.09408569 ... -0.75009155 -0.8735657
  -0.67297363]
 [ 0.06387329 0.11178589 0.15582275 ... -0.8456726 -0.99191284
  -0.7725525 ]], sr=44100 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  self.duration = librosa.core.get_duration(y,sr)
Traceback (most recent call last):
  File "C:\Users\MyUser\Remixatron\infinite_jukebox.py", line 262, in <module>
    jukebox = InfiniteJukebox(filename=args.filename, start_beat=args.start, clusters=args.clusters,
  File "C:\Users\MyUser\Remixatron\Remixatron.py", line 164, in __init__
    self.__process_audio()
  File "C:\Users\MyUser\Remixatron\Remixatron.py", line 455, in __process_audio
    beats[last_chance]['next'] = min(beats[last_chance]['jump_candidates'])
ValueError: min() arg is an empty sequence
-----------------------------------------------------------------------------------------------------
```
I have already installed the modules required for this application to work: youtube-dl, numpy, etc...
My operating system is Windows 10.

**Comment by drensin** [comment]
The first error is just that the code can't find the file you specified.  Have you tried specifying a complete path?

Additionally.. If you're on Windows then you should not be using the command line interface.  Instead, you should be using the Web UI.  See the README.MD in the /Web UI directory in the source tree for instructions.

Finally.. If you get the min() arg error after using the Web UI, try setting the clusters value to something small - like 4 - in the interface and trying again.

**Comment by SEGACD32XMODEL1** [comment]
min() arg error is also on the WebUI version

**Comment by drensin** [comment]
ok. try using the command line and specifying the number of clusters to use
by hand. For example, use:  -clusters 8  to use 8 clusters, etc.  Start
with 8 and see if it works.  If not, try 16.  If that doesn't work, then
something very weird is happening.
