### ISSUE TITLE
Problem installing dependencies (Web UI)

### ISSUE THREAD

**Issue by RaymondTracer** [drensin/Remixatron#27]
I'm running Windows 10 with Python 3.10.4, here is the log:

```
PS C:\Users\user\Documents\GitHub\Remixatron\Web UI> pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: appdirs in c:\users\user\appdata\roaming\python\python310\site-packages (from -r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: audioread in c:\users\user\appdata\roaming\python\python310\site-packages (from -r requirements.txt (line 2)) (3.0.0)
Collecting bidict
  Downloading bidict-0.22.0-py3-none-any.whl (36 kB)
Collecting Brotli
  Downloading Brotli-1.0.9-cp310-cp310-win_amd64.whl (383 kB)
     ---------------------------------------- 383.3/383.3 kB 11.7 MB/s eta 0:00:00
Requirement already satisfied: certifi in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (2022.6.15)
Requirement already satisfied: cffi in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (1.15.1)
Collecting chardet
  Downloading chardet-5.0.0-py3-none-any.whl (193 kB)
     ---------------------------------------- 193.6/193.6 kB ? eta 0:00:00
Requirement already satisfied: charset-normalizer in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (2.1.0)
Collecting click
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ---------------------------------------- 96.6/96.6 kB ? eta 0:00:00
Collecting Cython
  Downloading Cython-0.29.32-py2.py3-none-any.whl (986 kB)
     ---------------------------------------- 986.3/986.3 kB 65.1 MB/s eta 0:00:00
Collecting dbus-python
  Downloading dbus-python-1.3.2.tar.gz (605 kB)
     ---------------------------------------- 605.5/605.5 kB ? eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.ngc.nvidia.com
      Collecting meson-python>=0.8.1
        Downloading meson_python-0.8.1-py3-none-any.whl (17 kB)
      Collecting meson>=0.60.0
        Downloading meson-0.63.2-py3-none-any.whl (877 kB)
           ------------------------------------- 878.0/878.0 kB 28.0 MB/s eta 0:00:00
      Collecting ninja
        Downloading ninja-1.10.2.3-py2.py3-none-win_amd64.whl (292 kB)
           ---------------------------------------- 292.6/292.6 kB ? eta 0:00:00
      Collecting patchelf
        Downloading patchelf-0.15.0.0.tar.gz (150 kB)
           ---------------------------------------- 150.3/150.3 kB ? eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools
        Downloading setuptools-65.3.0-py3-none-any.whl (1.2 MB)
           ---------------------------------------- 1.2/1.2 MB 76.4 MB/s eta 0:00:00
      Collecting wheel
        Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting tomli>=1.0.0
        Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting colorama
        Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
      Collecting pyproject-metadata>=0.5.0
        Downloading pyproject_metadata-0.6.1-py3-none-any.whl (7.4 kB)
      Collecting packaging>=19.0
        Downloading packaging-21.3-py3-none-any.whl (40 kB)
           ---------------------------------------- 40.8/40.8 kB ? eta 0:00:00
      Collecting pyparsing!=3.0.5,>=2.0.2
        Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
           ---------------------------------------- 98.3/98.3 kB ? eta 0:00:00
      Building wheels for collected packages: patchelf
        Building wheel for patchelf (pyproject.toml): started
        Building wheel for patchelf (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Building wheel for patchelf (pyproject.toml) did not run successfully.
        exit code: 1

        [9 lines of output]
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-42fzc6mx\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 613, in setup
            cmkr = cmaker.CMaker(cmake_executable)
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-42fzc6mx\overlay\Lib\site-packages\skbuild\cmaker.py", line 141, in __init__
            self.cmake_version = get_cmake_version(self.cmake_executable)
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-42fzc6mx\overlay\Lib\site-packages\skbuild\cmaker.py", line 95, in get_cmake_version
            raise SKBuildError(
        Traceback (most recent call last):

        Problem with the CMake installation, aborting build. CMake executable is cmake
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
      Failed to build patchelf
      ERROR: Could not build wheels for patchelf, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Idol11112222** [comment]
Try updating python by downloading it from the original site. If that doesn't work, upgrade pip: pip install --upgrade pip
And also Download ffmpeg and place its .exe files in the folder where the web interface is located.

**Comment by RaymondTracer** [comment]
None of those suggestions worked, still same output.

**Comment by drensin** [comment]
have you tried installing CMake for Windows?  (https://cmake.org/download/)

**Comment by RaymondTracer** [comment]
That seemed to have helped, but I'm still getting errors and just before or at the end of trying to install the dependancies it opens a Linux bash script in Notepad++.

![image](https://user-images.githubusercontent.com/6290310/190842170-0575e5e7-423a-43b3-a34e-e841f20ae110.png)

```
PS C:\Users\user\Documents\GitHub\Remixatron\Web UI> pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: appdirs in c:\users\user\appdata\roaming\python\python310\site-packages (from -r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: audioread in c:\users\user\appdata\roaming\python\python310\site-packages (from -r requirements.txt (line 2)) (3.0.0)
Collecting bidict
  Downloading bidict-0.22.0-py3-none-any.whl (36 kB)
Collecting Brotli
  Downloading Brotli-1.0.9-cp310-cp310-win_amd64.whl (383 kB)
     ---------------------------------------- 383.3/383.3 kB 23.3 MB/s eta 0:00:00
Requirement already satisfied: certifi in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (2022.6.15)
Requirement already satisfied: cffi in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (1.15.1)
Collecting chardet
  Downloading chardet-5.0.0-py3-none-any.whl (193 kB)
     ---------------------------------------- 193.6/193.6 kB ? eta 0:00:00
Requirement already satisfied: charset-normalizer in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (2.1.0)
Requirement already satisfied: click in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (8.1.3)
Collecting Cython
  Downloading Cython-0.29.32-py2.py3-none-any.whl (986 kB)
     ---------------------------------------- 986.3/986.3 kB 65.1 MB/s eta 0:00:00
Collecting dbus-python
  Downloading dbus-python-1.3.2.tar.gz (605 kB)
     ---------------------------------------- 605.5/605.5 kB ? eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [176 lines of output]
      Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.ngc.nvidia.com
      Collecting meson-python>=0.8.1
        Downloading meson_python-0.8.1-py3-none-any.whl (17 kB)
      Collecting meson>=0.60.0
        Downloading meson-0.63.2-py3-none-any.whl (877 kB)
           ------------------------------------- 878.0/878.0 kB 27.1 MB/s eta 0:00:00
      Collecting ninja
        Downloading ninja-1.10.2.3-py2.py3-none-win_amd64.whl (292 kB)
           ---------------------------------------- 292.6/292.6 kB ? eta 0:00:00
      Collecting patchelf
        Downloading patchelf-0.15.0.0.tar.gz (150 kB)
           ---------------------------------------- 150.3/150.3 kB ? eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools
        Downloading setuptools-65.3.0-py3-none-any.whl (1.2 MB)
           ---------------------------------------- 1.2/1.2 MB 81.5 MB/s eta 0:00:00
      Collecting wheel
        Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting tomli>=1.0.0
        Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting pyproject-metadata>=0.5.0
        Downloading pyproject_metadata-0.6.1-py3-none-any.whl (7.4 kB)
      Collecting colorama
        Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
      Collecting packaging>=19.0
        Downloading packaging-21.3-py3-none-any.whl (40 kB)
           ---------------------------------------- 40.8/40.8 kB ? eta 0:00:00
      Collecting pyparsing!=3.0.5,>=2.0.2
        Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
           ---------------------------------------- 98.3/98.3 kB ? eta 0:00:00
      Building wheels for collected packages: patchelf
        Building wheel for patchelf (pyproject.toml): started
        Building wheel for patchelf (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Building wheel for patchelf (pyproject.toml) did not run successfully.
        exit code: 1

        [126 lines of output]
        Not searching for unused variables given on the command line.
        -- The C compiler identification is MSVC 19.33.31629.0
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx86/x64/cl.exe - skipped
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- The CXX compiler identification is MSVC 19.33.31629.0
        CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.24/Modules/CMakeDetermineCXXCompiler.cmake:162 (if):
          Policy CMP0054 is not set: Only interpret if() arguments as variables or
          keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
          details.  Use the cmake_policy command to set the policy and suppress this
          warning.

          Quoted variables like "MSVC" will no longer be dereferenced when the policy
          is set to NEW.  Since the policy is not set the OLD behavior will be used.
        Call Stack (most recent call first):
          CMakeLists.txt:4 (ENABLE_LANGUAGE)
        This warning is for project developers.  Use -Wno-dev to suppress it.

        CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.24/Modules/CMakeDetermineCXXCompiler.cmake:183 (elseif):
          Policy CMP0054 is not set: Only interpret if() arguments as variables or
          keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
          details.  Use the cmake_policy command to set the policy and suppress this
          warning.

          Quoted variables like "MSVC" will no longer be dereferenced when the policy
          is set to NEW.  Since the policy is not set the OLD behavior will be used.
        Call Stack (most recent call first):
          CMakeLists.txt:4 (ENABLE_LANGUAGE)
        This warning is for project developers.  Use -Wno-dev to suppress it.

        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx86/x64/cl.exe - skipped
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- Configuring done
        -- Generating done
        -- Build files have been written to: C:/Users/user/AppData/Local/Temp/pip-install-z6yi03vk/patchelf_d25802c4536144569c375606c83fc3b1/_cmake_test_compile/build
        -- The C compiler identification is MSVC 19.33.31629.0
        -- The CXX compiler identification is MSVC 19.33.31629.0
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx86/x64/cl.exe - skipped
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx86/x64/cl.exe - skipped
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- Configuring done
        -- Generating done
        CMake Warning:
          Manually-specified variables were not used by the project:

            PYTHON_EXECUTABLE
            PYTHON_INCLUDE_DIR
            PYTHON_LIBRARY
            PYTHON_VERSION_STRING
            Python3_EXECUTABLE
            Python3_INCLUDE_DIR
            Python3_LIBRARY
            Python_EXECUTABLE
            Python_INCLUDE_DIR
            Python_LIBRARY
            SKBUILD


        -- Build files have been written to: C:/Users/user/AppData/Local/Temp/pip-install-z6yi03vk/patchelf_d25802c4536144569c375606c83fc3b1/_skbuild/win-amd64-3.10/cmake-build
        [1/9] Creating directories for 'build_patchelf'
        [2/9] No download step for 'build_patchelf'
        [3/9] No update step for 'build_patchelf'
        [4/9] Performing patch step for 'build_patchelf'
        [5/9] Performing configure step for 'build_patchelf'
        FAILED: build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-configure C:/Users/user/AppData/Local/Temp/pip-install-z6yi03vk/patchelf_d25802c4536144569c375606c83fc3b1/_skbuild/win-amd64-3.10/cmake-build/build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-configure
        cmd.exe /C "cd /D C:\Users\user\AppData\Local\Temp\pip-install-z6yi03vk\patchelf_d25802c4536144569c375606c83fc3b1\src\patchelf-upstream && .\configure && "C:\Program Files\CMake\bin\cmake.exe" -E touch C:/Users/user/AppData/Local/Temp/pip-install-z6yi03vk/patchelf_d25802c4536144569c375606c83fc3b1/_skbuild/win-amd64-3.10/cmake-build/build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-configure"
        '.\configure' is not recognized as an internal or external command,
        operable program or batch file.
        ninja: build stopped: subcommand failed.
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-45k2h0uy\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 645, in setup
            cmkr.make(make_args, install_target=cmake_install_target, env=env)
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-45k2h0uy\overlay\Lib\site-packages\skbuild\cmaker.py", line 680, in make
            self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
          File "C:\Users\user\AppData\Local\Temp\pip-build-env-45k2h0uy\overlay\Lib\site-packages\skbuild\cmaker.py", line 704, in make_impl
            raise SKBuildError(


        --------------------------------------------------------------------------------
        -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator
        --------------------------------
        ---------------------------
        ----------------------
        -----------------
        ------------
        -------
        --
        --
        -------
        ------------
        -----------------
        ----------------------
        ---------------------------
        --------------------------------
        -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator - success
        --------------------------------------------------------------------------------

        Configuring Project
          Working directory:
            C:\Users\user\AppData\Local\Temp\pip-install-z6yi03vk\patchelf_d25802c4536144569c375606c83fc3b1\_skbuild\win-amd64-3.10\cmake-build
          Command:
            cmake 'C:\Users\user\AppData\Local\Temp\pip-install-z6yi03vk\patchelf_d25802c4536144569c375606c83fc3b1' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\user\AppData\Local\Temp\pip-install-z6yi03vk\patchelf_d25802c4536144569c375606c83fc3b1\_skbuild\win-amd64-3.10\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.10.7 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\user\AppData\Local\Temp\pip-build-env-45k2h0uy\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPython3_EXECUTABLE:FILEPATH=C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe' '-DPython3_INCLUDE_DIR:PATH=C:\Users\user\AppData\Local\Programs\Python\Python310\Include' '-DPython3_LIBRARY:PATH=C:\Users\user\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython_EXECUTABLE:FILEPATH=C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe' '-DPython_INCLUDE_DIR:PATH=C:\Users\user\AppData\Local\Programs\Python\Python310\Include' '-DPython_LIBRARY:PATH=C:\Users\user\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPYTHON_EXECUTABLE:FILEPATH=C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\user\AppData\Local\Programs\Python\Python310\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\user\AppData\Local\Programs\Python\Python310\libs\python310.lib' -DCMAKE_BUILD_TYPE:STRING=Release

        Traceback (most recent call last):

        An error occurred while building with CMake.
          Command:
            cmake --build . --target install --config Release --
          Install target:
            install
          Source directory:
            C:\Users\user\AppData\Local\Temp\pip-install-z6yi03vk\patchelf_d25802c4536144569c375606c83fc3b1
          Working directory:
            C:\Users\user\AppData\Local\Temp\pip-install-z6yi03vk\patchelf_d25802c4536144569c375606c83fc3b1\_skbuild\win-amd64-3.10\cmake-build
        Please check the install target is valid and see CMake's output for more information.
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
      Failed to build patchelf
      ERROR: Could not build wheels for patchelf, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by drensin** [comment]
ugh.. .I hate windows..  It wants to run autoconf tools to compile
something.  I don't know why other people aren't having this problem, but
it's affecting you.  I need to find a new/better delivery mechanism for
Remixatron for windows.

**Comment by lynatic1337** [comment]
Btw this problem still exists on macOS. This is not a Windows problem, it's a non-Linux problem.

**Comment by drensin** [comment]
Thanks to @SMarioMan , there's a docker install now.  Use that for non-Linux.  Instructions are in the readme.  This will be way easier for everyone.. :-)

**Comment by Bluepeltz** [comment]
Solved my frustrations with it, lol
