### ISSUE TITLE
Dependency issue on Python 3.12

### ISSUE THREAD

**Issue by pointydev** [drensin/Remixatron#30]
```
[pointy@pointy Web UI]$ pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: appdirs in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (1.4.4)
Collecting audioread (from -r requirements.txt (line 2))
  Using cached audioread-3.0.1-py3-none-any.whl.metadata (8.4 kB)
Collecting bidict (from -r requirements.txt (line 3))
  Using cached bidict-0.22.1-py3-none-any.whl (35 kB)
Requirement already satisfied: Brotli in /usr/lib64/python3.12/site-packages (from -r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: certifi in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (2023.5.7)
Requirement already satisfied: cffi in /usr/lib64/python3.12/site-packages (from -r requirements.txt (line 6)) (1.15.1)
Requirement already satisfied: chardet in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (5.2.0)
Requirement already satisfied: charset-normalizer in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (3.2.0)
Requirement already satisfied: click in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (8.1.3)
Collecting Cython (from -r requirements.txt (line 10))
  Using cached Cython-3.0.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: dbus-python in /usr/lib64/python3.12/site-packages (from -r requirements.txt (line 11)) (1.3.2)
Requirement already satisfied: decorator in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 12)) (5.1.1)
Requirement already satisfied: dnspython in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (2.4.2)
Collecting eventlet (from -r requirements.txt (line 14))
  Using cached eventlet-0.33.3-py2.py3-none-any.whl (226 kB)
Collecting ffmpeg-python (from -r requirements.txt (line 15))
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting Flask (from -r requirements.txt (line 16))
  Using cached flask-3.0.0-py3-none-any.whl.metadata (3.6 kB)
Collecting Flask-Compress (from -r requirements.txt (line 17))
  Using cached Flask_Compress-1.14-py3-none-any.whl.metadata (7.8 kB)
Collecting Flask-SocketIO (from -r requirements.txt (line 18))
  Using cached Flask_SocketIO-5.3.6-py3-none-any.whl.metadata (2.6 kB)
Collecting greenlet (from -r requirements.txt (line 19))
  Using cached greenlet-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: idna in /usr/lib/python3.12/site-packages (from -r requirements.txt (line 20)) (3.4)
Collecting itsdangerous (from -r requirements.txt (line 21))
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting Jinja2 (from -r requirements.txt (line 22))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting joblib (from -r requirements.txt (line 23))
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting librosa (from -r requirements.txt (line 24))
  Using cached librosa-0.10.1-py3-none-any.whl.metadata (8.3 kB)
Collecting llvmlite (from -r requirements.txt (line 25))
  Using cached llvmlite-0.41.1.tar.gz (146 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting madmom (from -r requirements.txt (line 26))
  Using cached madmom-0.16.1.tar.gz (20.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/pointy/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pointy/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/pointy/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-a75icbe1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-a75icbe1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-a75icbe1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-a75icbe1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Fedora 39, Python 3.12, pip 23.3.1, cloned Remixatron c6e0858

Thanks,
Elliott

**Comment by drensin** [comment]
1) This isn't going to work with Python 3.12.  The madmom library only works below Python 3.10.  My advice is to install Python 3.8 (which works great) and try again

2) The problem is in the error message. You need to install the Cyhon package first. (not sure why pip isn't getting the dependency order correct).  After you install Python 3.8, run this:

pip install Cython, numpy
pip install -r requirements.txt
