### ISSUE TITLE
AttributeError: module 'madmom' has no attribute 'features'

### ISSUE THREAD

**Issue by OhaDerErste** [drensin/Remixatron#31]
I am running Remixatron web UI in a fresh venv on Arch Linux and getting this error once computing pitch data has finished.
```fetch complete
10.0%: Audio downloaded
10.0%: loading file and extracting raw audio
20.0%: computing pitch data...
30.0%: Running a high precision beat finding algorithm. This could take up to 2 minutes...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/oha/Remixatron/Web UI/main.py", line 447, in process_audio
    jukebox = InfiniteJukebox(fn, clusters=clusters,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oha/Remixatron/Web UI/Remixatron.py", line 169, in __init__
    self.__process_audio_madmom()
  File "/home/oha/Remixatron/Web UI/Remixatron.py", line 578, in __process_audio_madmom
    proc = madmom.features.DBNDownBeatTrackingProcessor(beats_per_bar=[3, 4], fps=100)
           ^^^^^^^^^^^^^^^
AttributeError: module 'madmom' has no attribute 'features'
```

**Comment by drensin** [comment]
did you follow the new installation instructions?  you have to clone the
madmom repo (it's in the README).

See here: https://github.com/drensin/Remixatron/blob/master/Web%20UI/README.md

**Comment by OhaDerErste** [comment]
removed and cloned the repo again. same error

**Comment by drensin** [comment]
Did you follow the step to clone the mad mom repo, too?

**Comment by OhaDerErste** [comment]
yeah. copy and pasted all the commands from the install instructions. Only thing I did differently was that I created a python venv inside of "Web UI"

**Comment by drensin** [comment]
Hmm. Ok. I'll look into it this weekend

**Comment by OhaDerErste** [comment]
thanks. Project looks pretty cool, btw

**Comment by drensin** [comment]
hmm.. I can't reproduce this on a clean Ubuntu VM.  Please open a terminal in the "Remixatron/Web UI/" directory and try the following:

cd madmom
python setup.py develop --user
cd ..
python main.py

**Comment by OhaDerErste** [comment]
still getting the same error. any other ideas?

**Comment by drensin** [comment]
one last thing..  instead of using venv, try using conda instead? Just follow the instructions from the top of the README.

I'm not sure why your venv isn't seeing the full madmom package installed.

**Comment by OhaDerErste** [comment]
getting the exact same error with conda

**Comment by Cwarren2025** [comment]
Sorry but I am also getting the same error. Thanks!
<img width="710" alt="Screenshot 2024-04-07 at 11 20 03 PM" src="https://github.com/drensin/Remixatron/assets/112130192/ec443818-82e9-43c1-a131-9d065caba68f">
