### ISSUE TITLE
Yet another Playback error.....

### ISSUE THREAD

**Issue by BoZ-Niko663** [drensin/Remixatron#32]
After going through and reinstalling tons of dependencies, I finally chose to upgrade to 64 Bit Python, that solved all the previous errors I encountered, however now I get this..

`C:\Users\CAPITAN HAMBURGUEZA\Music\Remixatron>python rplayer.py "1_r2r test_(Instrumental).wav"
pygame 2.5.2 (SDL 2.28.3, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "rplayer.py", line 262, in <module>
    jukebox = InfiniteJukebox(filename=args.filename, start_beat=args.start, clusters=args.clusters,
  File "C:\Users\CAPITAN HAMBURGUEZA\Music\Remixatron\Remixatron.py", line 164, in __init__
    self.__process_audio()
  File "C:\Users\CAPITAN HAMBURGUEZA\Music\Remixatron\Remixatron.py", line 190, in __process_audio
    self.duration = librosa.core.get_duration(y,sr)
TypeError: get_duration() takes 0 positional arguments but 2 were given`

Seems to have something to do with a function being re-defined based on my 5 second research, any ideas what to do? I've been struggling so much to get this thing working, help is greatly appreciated.

**Comment by drensin** [comment]
you seem to be using the command line interface?  That's deprecated.
Please run the Web UI.

**Comment by BoZ-Niko663** [comment]
😢  The command line's more convenient for me...

It seems the Web UI's takes a long time to set up, but I could be wrong. You can load your own music on the Web UI right? I'll try that then.

Aren't there any tutorial videos around? I think I'll manage without but it would be helpful

**Comment by drensin** [comment]
I got a lot of feedback from people saying that the command line was just
too hard to use and they wanted something simpler. That's why I built the
Web UI. Sorry... It's an open source project maintained by one person in
his spare time, so there's only so much I'm likely to get done in any given
month 🙂
