### ISSUE TITLE
Remixatron crashes when trying to display playback progress

### ISSUE THREAD

**Issue by GoldenChaos** [drensin/Remixatron#9]
Just downloaded the newest version to give some of the changes a go. However, I get this error when it tries to display playback progress:

```
##Traceback (most recent call last):---###--###---#####---####--##-----###--###---#####---#####-----####-----###----######---#
##----####------##----###--------###  File "/Users/Jason/Sites/Remixatron/infinite_jukebox.py", line 319, in <module>####---##
###-----####-----###----######---###----####------##----###--------#####-                                                display_playback_progress(v)
2019-07-28 11:31:43.125  File "/Users/Jason/Sites/Remixatron/infinite_jukebox.py", line 119, in display_playback_progresshe (null) framework.                                                                                                              curses.A_REVERSE)                      # print in reverse highlight
                                                                  _curses.error: addch() returned ERR
```

The song plays for one beat before pygame crashes and audio stops playing.

**Comment by drensin** [comment]
ugh... I can't reproduce this.. OK.. A couple of things to try..

please do the following in the Remixatron directory:

pip install -r requirements.txt

Also, please be sure to be running at LEAST Python 3.5, though 3.6+ would
be better.  Python 2.7 is going away on Jan 1 and librosa is really flaky
with < 3.5.

-dave

**Comment by GoldenChaos** [comment]
I'm running Python 3.7.4 here. Requirements successfully installed (as they had before) - no change, same error.

Perhaps worth mentioning that I'm running macOS Catalina beta, but I'm not sure why that would cause an issue in this specific instance since I'm using my own installation of python through homebrew.

**Comment by GoldenChaos** [comment]
The recent update slightly changed the error display. Here’s the new error:

```
 [##########] finished processing

    filename: 1-03 Phoenix Wright_ Ace Attorney - Court Begins.mp3
    duration: 00:01:46
       beats: 331
       tempo: 199 bpm
    clusters: 30
    segments: 101
  samplerate: 44100

###-####------######-####-----####---##---##---###---##--###----16Traceback (most recent call last):###--------#--##-----#------##--####-------#--##-----######-
----####------#-----  File "/Users/Jason/Sites/Remixatron/infinite_jukebox.py", line 319, in <module>--########-##--#####-######--##----#######-##--####-------#
####----###              display_playback_progress(v)
                                                       File "/Users/Jason/Sites/Remixatron/infinite_jukebox.py", line 139, in display_playback_progression 'SLSIsSuppressedByScreenTime' can't be found in the (null) framework.           window.addstr(y_pos, x_pos, buj_disp, curses.A_BOLD | curses.A_REVERSE | curses.A_STANDOUT )
       _curses.error: addwstr() returned ERR
```

**Comment by drensin** [comment]
hmm... the curses library on your system seems 'broken' somehow..  I'll
poke at this more in the next couple of days when I can get in front of my
mac.

**Comment by drensin** [comment]
Well.. I've been working for a couple of weeks on a real UI for this. I've now just uploaded it here: https://github.com/drensin/Remixatron/tree/master/Web%20UI.

In general, the curses library used in the CLI is a problematic, so I'm slowly going to deprecate it. Please poke at the web ui and let me know what you think :-)

**Comment by GoldenChaos** [comment]
Oh, awesome! Will do, been waiting for this for a looooong time 😄
